# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomCamera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomCamera
#  pod 'GPUImage'
#   pod 'GPUImage2', :podspec => './GPUImage2.podspec'
  pod 'SnapKit', '4.2.0'
end

